<?php if($this->user): ?>
    <form method="post" action="addAerolinea">
        <div class="mb-3">
                <label for="Nombre" class="form-label">
                    Nombre:
                </label>
                <input name="Nombre" type="text" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="Pais" class="form-label">
                    Pais:
                </label>
                <input name="Pais" type="text" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="Fundacion" class="form-label">
                    Fundacion:
                </label>
                <input name="Fundacion" type="text" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="servicios" class="form-label">
                    Servicios:
                </label>
                <input name="servicios" type="text" class="form-control" required>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Agregar Aerolinea</button>
    </form>
<?php endif;?>