<?php require './templates/layouts/header.phtml'; ?>

<?php require './templates/add_aerolinea.phtml'; ?>

<br>

<ul class="list-group">
    <?php if(isset($aerolineas)): ?>
        <?php foreach($aerolineas as $aerolinea): ?>
            <li class="list-group-item item-aerolinea d-flex justify-content-between align-items-center">
                <span>
                    <b><?=$aerolinea->Nombre; ?></b>
                </span>
                <span class="actions">
                    <button type="button" class="btn btn-success btn-sm">
                        <a href="detallesaerolinea/<?=$aerolinea->id;?>" class="text-white">Mas info</a>
                    </button>
                    <button type="button" class="btn btn-danger btn-sm ml-2">
                        <a href="deleteAerolinea/<?=$aerolinea->id;?>" class="text-white">Eliminar</a>
                    </button>
                    <button type="button" class="btn btn-warning btn-sm ml-2">
                        <a href="showEditAerolinea/<?=$aerolinea->id;?>" class="text-white">Editar</a>
                    </button>
                </span>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>

<?php require './templates/layouts/footer.phtml'; ?>